name: Cypress Tests

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run [Chrome]
        uses: cypress-io/github-action@v5.0.5
        with:
          browser: chrome
        env:
          CYPRESS_username: ${{ secrets.SWAG_USERNAME }}
          CYPRESS_password: ${{ secrets.SWAG_PASSWORD }}