name: Cypress Tests

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run [Chrome]
        uses: cypress-io/github-action@v5.0.5
        with:
          browser: chrome
        env:
          CYPRESS_username: ${{ secrets.SWAG_USERNAME }}
          CYPRESS_password: ${{ secrets.SWAG_PASSWORD }}
      - name: Saving screenshot on failure   
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Saving screenshot on failure
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos